# Generated by Django 5.2.8 on 2025-11-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangjobs',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bangjobs',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bangjobs',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='biharjobs',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='biharjobs',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='biharjobs',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
